Repository spotbugs/spotbugs, pull requests merged in 2018-11, with the labels that each got.

#793 Fix issue #702
  CHANGELOG.md
  spotbugs/src/main/java/edu/umd/cs/findbugs/detect/UnreadFields.java
Labels: enhancement

#794 Add missing "a" in bot message
  .github/config.yml
Labels: documentation

#804 Stop updating global var, use local var to store temporal debug flag
  CHANGELOG.md
  spotbugs/src/main/java/edu/umd/cs/findbugs/ba/Dataflow.java
Labels: bug

#808 bump up Gradle to 5.0 stable
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build
