Repository spotbugs/spotbugs, pull requests merged in 2020-07, with the labels that each got.

#1184 Experimental support for the SARIF 2.1.0 report
  spotbugs/build.gradle
  spotbugs/src/main/java/edu/umd/cs/findbugs/BugPattern.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/DetectorFactoryCollection.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/ba/SourceFinder.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/BugCollectionAnalyser.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Extension.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Level.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Location.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Message.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Notification.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Result.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Rule.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/SarifBugReporter.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/SarifException.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/Stack.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/package-info.java
  spotbugs/src/test/java/edu/umd/cs/findbugs/SAXBugCollectionHandlerTest.java
  spotbugs/src/test/java/edu/umd/cs/findbugs/sarif/LevelTest.java
  spotbugs/src/test/java/edu/umd/cs/findbugs/sarif/SarifBugReporterTest.java
Labels: enhancement, help wanted

#1186 Add a missing ja document for #1183
  spotbugs/etc/messages_ja.xml
Labels: documentation

#1199 docs: remove colgroup element that is not supported by Java 8
  spotbugs/src/main/java/edu/umd/cs/findbugs/sarif/package-info.java
Labels: documentation

#1224 Pack log4j-api to distribution zip/tar
  spotbugs/build.gradle
Labels: build

#1070 Custom bug annotation support
  CHANGELOG.md
  spotbugs/build.gradle
  spotbugs/src/main/java/edu/umd/cs/findbugs/BugAnnotation.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/SAXBugCollectionHandler.java
  spotbugs/src/main/java/edu/umd/cs/findbugs/VersionInsensitiveBugComparator.java
  spotbugs/src/test/java/edu/umd/cs/findbugs/VersionInsensitiveBugComparatorTest.java
Labels: enhancement
