Repository spotbugs/spotbugs, pull requests merged in 2020-02, with the labels that each got.

#1076 Upload distributions onto GitHub Releases too
  .travis.yml
  docs/conf.py
Labels: build

#1091 Be precise about required Ctor accessibility
  spotbugs/etc/messages.xml
Labels: documentation

#1088 Correct XSL variable declaration & assignment
  CHANGELOG.md
  spotbugs/src/xsl/default.xsl
  spotbugs/src/xsl/plain.xsl
Labels: bug
